### ISSUE TITLE
Information on using this with Home Assistant

### ISSUE THREAD

**Issue by smbunn** [iphong/esphome-tuya-curtain#1]
Do you have a guide on how to add this to Home Assistant?
Where does your yaml and .h files go and how do you set this up in 'integrations' or configuration.yaml?

**Comment by iphong** [comment]
This is an ESPHome implementation. You need to build it with esphome and flash it onto to ESP8266 chip on the motor controller.

Since ESPHome works natively with homeAssistant, it should be automatically discovered.

Let me know if you need further help.
